config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :items do
  	resources :reviews
  end
  root 'items#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
	belongs_to :user
	belongs_to :category
	has_many :reviews

	has_attached_file :item_img, styles: { :item_index => "250x350>", :show_item => "320x475>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :item_img, content_type: /\Aimage\/.*\z/
end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :item
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :items
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	before_action :find_item, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, only: [:new, :edit]
	def index
		if params[:category].blank?
			@items = Item.all.order("created_at DESC")
		else
			@category_id = Category.find_by(name: params[:category]).id
			@items = Item.where(:category_id => @category_id).order("created_at DESC")
		end
	end

	

	def show
		if @item.reviews.blank?
			@average_review = 0
		else
			@average_review = @item.reviews.average(:rating).round(2)
		end

	end

	def new 
		@item = current_user.items.build
		@categories = Category.all.map{ |c| [c.name, c.id]}
	end

	def create
		@item = current_user.items.build(item_params)
		@item.category_id = params[:category_id]

		if @item.save 
			redirect_to root_path
		else
			render 'new'
		end
	end

	def edit
		
		@categories = Category.all.map{ |c| [c.name, c.id]}
	end

	def update

		@item.category_id = params[:category_id]
		if @item.update(item_params)
			redirect_to item_path(@item)
		else
			render 'edit'
		end
	end

	def destroy
			@item.destroy
			redirect_to root_path
	end



	private

		def item_params
			params.require(:item).permit(:title, :description, :maker, :category_id, :item_img)
		end

		def find_item
			@item = Item.find(params[:id])
		end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

	before_action :find_item
	before_action :find_review, only: [:edit, :update, :destroy]
	before_action :authenticate_user!, only: [:new, :edit]

	def new
		@review = Review.new
	end
	

	def create
		@review = Review.new(review_params)
		@review.item_id = @item.id
		@review.user_id = current_user.id
		
		if @review.save
			redirect_to item_path(@item)
		else
			render 'new'
			

		end

	end

	def edit 
	end

	def destroy
		@reviews.destroy
		redirect_to item_path(@item)
	end

	def update
		@review = Review.find(params[:id])
		if @review.update(review_params)
			redirect_to item_path(@item)
		else
			render 'edit'
		end
	end

	private
		def review_params
			params.require(:review).permit(:rating, :comment, :title)
		end
		def find_item
			@item = Item.find(params[:item_id])
		end
		def find_review
			@review = Review.find(params[:id])
		end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/items/_form.html.erb
<%= simple_form_for @item, :html => { :multipart => true } do |f|  %>

<div class="row new-review-form-row">
	<div class="col-md-6">
		<%= select_tag(:category_id, options_for_select(@categories), class: "form form-group form-control", :prompt => "Select a category") %>
	</div>
	<div class="col-md-6">
		<%= f.file_field :item_img, class: "form form-group form-control" %>
	</div>

</div>
<%= f.input :title, label: "Item Title" %>
<%= f.input :description %>
<%= f.input :maker %>

<%= f.button :submit, class: "btn-custom", style: "margin-left:0px;" %>

<% end %>

app/views/items/edit.html.erb
<div class="col-md-6 col-md-offset-3">
	<div class="new-item-form">
		<h1> Edit Item </h1>

		<%= simple_form_for @item, :html => { :multipart => true } do |f| %>
		<div class="new-review-form-row">
			<div class="col-md-6">
			<%= f.select :category_id, @categories, class: "form form-group form-control" %>

			</div>
			<div class="col-md-6">
				<%= f.file_field :item_img,  class: "form form-group form-control" %>
			</div>
		</div>
		<%= f.input :title, label: "Item Title" %>
		<%= f.input :description %>
		<%= f.input :maker %>

		<%= f.button :submit, class: "btn-custom", style: "margin-left:0px;"  %>

		<% end %>
	</div>
</div>

app/views/items/index.html.erb
<h1 class="current-category">Category:  <%= params[:category] %></h1>
<% if @items.count == 0 %>
	<h3>There are currently no books in the category</h3>
<% else %>
	<div class="row">
		<% @items.each do |item| %>
			<div class="col-md-3">
				<a href="/items/<%=item.id %>">
					<%= image_tag item.item_img.url(:item_index), class: "index-item" %>
				</a>
			</div>
		<% end %>
	</div>	
<% end %>

app/views/items/new.html.erb
<div class="col-md-6 col-md-offset-3">
	<div class="new-item-form">
		<h1>New Item</h1>
		<%= render 'form' %>
	</div>
</div>

app/views/items/show.html.erb
<div class="container">
	<div class="row" style="margin-bottom:30px;">
		<div class="col-md-12" style="margin-left:0px;">
		<%= link_to "Back to Browse", root_path, class: "btn-custom", style:"margin-left:0px;" %>
		</div>
	</div>
	<div class="row" >
		<div class="col-md-4">
			<%= image_tag @item.item_img.url(:show_item), class: "show-item" %>
		</div>
		<div class="col-md-8 info-item">

			<h1 class="item.title"><%= @item.title %></h1>
			<h2 class="item.maker">Made by <%= @item.maker %></h2>
			<h3 style="margin-bottom:0px;">Average Rating</h3>
			<div class="review-summary-block">
			<div class="average-review-rating" data-score=<%= @average_review %>></div>
				<span class="number-of-reviews">Based on reviews from <%= @item.reviews.count %> users like you!</span>
			</div>
			<h4 class="item-description"><%= @item.description %></h4>
			




			<%= link_to "Edit", edit_item_path(@item), class: "btn-custom2 pull-right" %>

			<% if user_signed_in? %>
				<% if @item.user_id == current_user.id %>
					<%= link_to "Delete", item_path(@item), class: "btn-custom2 pull-right", method: :delete, data: {confirm: "Are you sure?"} %>
				<% end %>
			<% end %>

			<div class="col-md-12 review-section">
				<div class="col-md-6">
				<h1>Reviews</h1>
				</div>
				<div class="col-md-6">
					<div class="col-md-12" style="padding-right:0px;">
						<%= link_to "Add Review", new_item_review_path(@item), class: "btn-custom pull-right" %>
					</div>
				</div>
				<div class="col-md-12 review-comment-section">
					<div class="col-md-12">
						<%= render @item.reviews %>
					</div>
				</div>	
			</div>
		</div>
	</div>	
	<div class="row">
		
	</div>
</div>	



<script>
		$('.review-rating').raty({
			readOnly: true,
			score: function () {
				return $(this).attr('data-score');
			},
			path: '/assets/'
		});
</script>

<script>
		$('.average-review-rating').raty({
			readOnly: true,
			score: function () {
				return $(this).attr('data-score');
			},
			path: '/assets/'
		});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-default">

      <div class="container">
        <div class="navbar-header">
          <%=link_to "Review Anything", root_path, class: "navbar-brand" %>
        </div>
        <ul class="nav navbar-nav">
          
          <% if user_signed_in?  %>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %> </li>
          <% else %>
            <li><%= link_to "Sign Up", new_user_registration_path%></li>
            <li><%= link_to "Login", new_user_session_path %></li> 

          <% end %>
        </ul>

        <ul class="nav navbar-nav pull-right">

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Categories <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <% Category.all.each do |category| %>
                <li class="<%= 'active' if params[:category] == category.name %>">
                  <%= link_to category.name, items_path(category: category.name), class: "link" %>
                </li>
              <%end%>
            </ul>
          </li>

          <% if user_signed_in?  %>
            <li><%= link_to "Review Something New", new_item_path%> </li>
          <% else %>
            <li><%= link_to "Login", new_user_session_path %></li> 
          <% end %>

        </ul>
      </div>

    </nav>



    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/reviews/_form.html.erb
<%= simple_form_for([@item, @item.reviews.build]) do |f|%>
	
	<div id="rating-form">


	<label>Rating: </label>

	</div>

	<%= f.input :title %>
	<%= f.input :comment %>
	<%= f.button :submit %>
<% end %>


<script>
	$('#rating-form').raty({
		path: '/assets/',
		scoreName: 'review[rating]'
	});
</script>

app/views/reviews/_review.html.erb
<div class="row review-block">
<h3 class="review-title"> <%= review.title %></h3>
<div class="review-rating" data-score="<%= review.rating %>"></div>

<p class="review-comment"> <%= review.comment %></p>


<% if user_signed_in? %>
	<% if review.user_id == current_user.id %>
		
		<%= link_to "Delete", item_review_path(review.item, review), class: "btn-custom2-small pull-right ", method: :delete, data: {confirm: "Are you sure?"} %>
		<%= link_to "Edit", edit_item_review_path(review.item, review), class: "btn-custom-small pull-right" %>
	<% end %>
<% end %>
</div>

app/views/reviews/edit.html.erb
<h1>Edit Review</h1>
<%= simple_form_for([@item, @review]) do |f| %>
	<div id="rating-form">


	<label>Rating: </label>

	</div>
	<%= f.input :title %>
	<%= f.input :comment %>
	<%= f.button :submit %>
<% end %>

<script>
	$('#rating-form').raty({
		path: '/assets/',
		scoreName: 'review[rating]'
	});
</script>

app/views/reviews/new.html.erb
<div class="col-md-6 col-md-offset-3">
	<div class="new-item-form">
		<h1>New Review</h1>
		<%= render 'form' %>
	</div>
</div>